-- Agregar una clomna
ALTER TABLE alumno
ADD telefono VARCHAR (20) NOT NULL
GO
--AGREGAR MAS DE UNA COLUMNA
ALTER TABLE alumno
ADD 
curp VARCHAR (18),
matricula VARCHAR (13) NOT NULL;


--MODIFICAR UN TIPO DE DATO 
ALTER TABLE alumno
ALTER COLUMN telefono VARCHAR (30);
GO

--AGREGAR RESTRICCIONES
--PRIMARY KEY

--ESTE CODIGO CREA UNA TABLA CON 0 REGISTRO APARTIR DE OTRA

SELECT TOP 0 *
INTO alumno2
FROM alumno;
--ESTA COLUMNA OBTINE LOS NOMBRES DE LAS RESTRCCIONES 
SELECT *
FROM sys.objects AS o
WHERE o.parent_object_id = OBJECT_ID ('alumno2')
AND o.type IN ('PK', 'F', 'UQ', 'C', 'D')
ORDER BY o.type_desc;
--PRIMARY KEY
ALTER TABLE alumno2
ADD CONSTRAIN pk_alumno2
PRIMARY KEY (num_alumno);

--CREAR UNA TAABLA PARA LA FOREING KEY

CREATE TABLE carrera ( 
    carrera_id INT NOT NULL IDENTITY (1,1)
    PRIMARY KEY,
    nombre VARCHAR(25) NOT NULL
    );
    GO

ALTER TABLE alumnO2
ADD carrera_id INT;

ATER TABLE alumno2 
ADD CONSTRAIN FK_alumno2_carrera
FOREING KEY (carrera_id)
REFERENCE carrera (carrera_id)
ON DELETE CASCADE 
ON UPDATE NO ACTION;


--AGREGAR UN CHECK
ALTER TABLE alumno2
ADD CONSTRAIN ck_alumno2_telefono
CHECK (telefono LIKE '  ');


--AGREGAR UN DEFAULT
ALTER TABLE alumno2
ADD activo BIT NOT NULL;


ALTER TABLE alumno2
ADD CONSTRAINT dk_alumno2_activo
DEFAULT 1
FOR activo;

-- INIQUE 
ALTER TABLE alumn2
ADD CONSTRAINT uq_alumno2_matricula
UNIQUE (matricula);

--ELIMINAR RESTRICCIONES

--ELIMINAR FOREING KEY
ALTER TABLE alumno2
DROP CONSTRAINT fk_alumno2_carrera;

--ELIMINAR PRIMARY KEY
ALTER TABLE alumno2
DROP CONSTRAINT pk_alumno2;

ALTER TABLE alumno2
DROP CONSTRAINT pk_carrera;

--ELIMINAR UNQIUE
ALTER TABLE alumno2
DROP CONSTRAINT uq_alumno2_matricula;

--ELIMINAAR CHECK
ALTER TABLE alumno2
DROP CONSTRAINT ck_alumno2_telefono;

--ELIMINAR UNA COLUMNA
ALTER TABLE alumno2
DROP COLUMN matricula;

--DROP 
-- ELININAR LA TABLA ALUMNO
ALTER TABLE alumno2;
--ELIMINAR MAS DE UNA TABLA DE UNA A LA VEZ
DROP TABLE alumno, carrera;
--ELIMINAR BASE DE DATOS
USE MASTER;
IF DB_ID ('prueba atributos') IS NOT NULL
BEGIN 
    DROP DATABASE pruebaatributos;
END     

--MUESTRA LOS DATOS DE UNA TABLA POR CODIGO
SELECT 
COLUMN_NAME,
DATA_TYPE
CAHRACTER_MAXIMUM_LENGTH
IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'alumno';



--Ejercicio 5









